### ISSUE TITLE
Implementation discuession

### ISSUE THREAD

**Issue by WANG-KX** [dalmia/siren#5]
Hi,
I also implemented my version of SIREN according to the paper, and I have done several tests with it. My implementation is here [SIREN-2d](https://github.com/WANG-KX/SIREN-2D) .

I haven't run your code yet but have two questions.

1) the weight initialization of your code applies w0 to the result of linear output [link](https://github.com/dalmia/siren/blob/06eb2852eb035b940c9272efd8a1aa4d5541dbe9/siren/siren.py#L25). In the paper, seems that w0 is only applied to the weight*input without the bias. I'm not sure if my understanding is correct.

2) In the paper, SIREN is also used to fit image gradient. It's not clear that the SIREN gradient is calculated in an analytically way or not. Since the authors explicitly give out its analytical gradient, I think it should be in an analytically way. However, I cannot converge in this setting. Could you also provide such tests, or try my code to check if my understanding is correct.

I will give more tests when I have time.

**Comment by scart97** [comment]
Regarding the first question, I also implemented Siren [here](https://github.com/scart97/Siren-fastai2) and tried both w0 multiplying only the W matrix of the linear layer like in the paper or multiplying the whole result of the linear layer. The training results were the same in the end, and this change makes the implementation similar to other activation functions, so it's not tied to the linear layer.

**Comment by crysoberil** [comment]
Do you see faster convergence for the experiments you run? I tried it for fitting 2D shapes, and with the default setting did not get fast convergence.

**Comment by WANG-KX** [comment]
Hi, I do observe some improvements in convergence and I plotted the result in my project. https://github.com/WANG-KX/SIREN-2D.

Since the official implementation is open to the public, I think further discussion can be moved under that project.
